### ISSUE TITLE
Compile Errors 02

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#248]
Error	4	error MSB4018: The "CustomBuild" task failed unexpectedly.
System.IO.IOException: The process cannot access the file 'C:\Users\Red Castle\AppData\Local\Temp\tmpd96afe1753e1451d90e03214ccfacd8f.cmd' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	QuestScripts

**Comment by Zyres** [comment]
@Nupper I tried: 
- [X] msvc 2013 Win32 Release
- [X] msvc 2013 Win32 Debug 
- [X] msvc 2013 x64 Release 
- [X] msvc 2013 x64 Debug
Everything looks fine for me... When does this error appears? Did you cleaned the cmake chache?
![cmake-cache](http://i.imgur.com/JPIGz39.jpg)
And which compiler do you use?

**Comment by Cronicman** [comment]
cannot reproduce, using VS 2013 community
